/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomerDetails {
  'name' : string,
  'address' : string,
  'contactNumber' : string,
  'destinationLocation' : string,
  'pickupLocation' : string,
}
export interface DeliveryOrder {
  'id' : bigint,
  'status' : OrderStatus,
  'customer' : CustomerDetails,
  'createdAt' : Time,
  'lastUpdated' : Time,
  'parcelSize' : string,
  'deliveryProof' : [] | [ExternalBlob],
  'distanceRange' : [bigint, bigint],
  'price' : bigint,
  'riderContact' : [] | [string],
  'riderAssignment' : [] | [string],
}
export type ExternalBlob = Uint8Array;
export type OrderStatus = { 'pending' : null } |
  { 'picked' : null } |
  { 'delivered' : null };
export interface Rate {
  'largeParcelPrice' : bigint,
  'minDistance' : bigint,
  'maxDistance' : bigint,
  'smallParcelPrice' : bigint,
}
export interface RiderApplication {
  'hasBike' : boolean,
  'area' : string,
  'name' : string,
  'mobile' : string,
  'applicationTime' : Time,
}
export interface RiderProfile {
  'hasBike' : boolean,
  'area' : string,
  'name' : string,
  'mobile' : string,
  'assignedOrders' : Array<bigint>,
}
export interface SiteContent {
  'servicesList' : string,
  'contactNumber' : string,
  'whatsappTemplate' : string,
  'howItWorks' : string,
  'rates' : Array<Rate>,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addRate' : ActorMethod<[Rate], undefined>,
  'addRiderProfileInternal' : ActorMethod<
    [string, string, string, boolean],
    undefined
  >,
  'applyAsRider' : ActorMethod<[string, string, boolean, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignRiderToOrderInternal' : ActorMethod<[bigint, string], undefined>,
  'createOrderInternal' : ActorMethod<
    [CustomerDetails, string, [bigint, bigint], bigint],
    bigint
  >,
  'getAllOrdersInternal' : ActorMethod<[], Array<DeliveryOrder>>,
  'getAllRiderProfilesInternal' : ActorMethod<[], Array<RiderProfile>>,
  'getAssignedDeliveries' : ActorMethod<[Principal], Array<DeliveryOrder>>,
  'getAssignedDeliveriesForRiderInternal' : ActorMethod<
    [string],
    Array<DeliveryOrder>
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactNumber' : ActorMethod<[], string>,
  'getDeliveryProof' : ActorMethod<[bigint], [] | [ExternalBlob]>,
  'getDeliveryProofForOrderInternal' : ActorMethod<
    [bigint],
    [] | [ExternalBlob]
  >,
  'getOrderDetailsInternal' : ActorMethod<[bigint], DeliveryOrder>,
  'getRates' : ActorMethod<[], Array<Rate>>,
  'getRiderApplications' : ActorMethod<[], Array<RiderApplication>>,
  'getSiteContent' : ActorMethod<[], SiteContent>,
  'getWhatsAppTemplate' : ActorMethod<[], string>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeOrderInternal' : ActorMethod<[bigint], undefined>,
  'removeRate' : ActorMethod<[[bigint, bigint]], undefined>,
  'updateDeliveryStatus' : ActorMethod<
    [Principal, bigint, OrderStatus],
    undefined
  >,
  'updateOrderStatusInternal' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateOrderWithProofOfDeliveryInternal' : ActorMethod<
    [bigint, ExternalBlob],
    undefined
  >,
  'updateOrderWithRiderInternal' : ActorMethod<
    [bigint, string, string],
    undefined
  >,
  'updateSiteContent' : ActorMethod<
    [
      [] | [string],
      [] | [string],
      [] | [Array<Rate>],
      [] | [string],
      [] | [string],
    ],
    undefined
  >,
  'uploadDeliveryProofInternal' : ActorMethod<
    [bigint, ExternalBlob],
    undefined
  >,
  'uploadProofOfDelivery' : ActorMethod<
    [Principal, bigint, ExternalBlob],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];