/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Rate = IDL.Record({
  'largeParcelPrice' : IDL.Nat,
  'minDistance' : IDL.Nat,
  'maxDistance' : IDL.Nat,
  'smallParcelPrice' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CustomerDetails = IDL.Record({
  'name' : IDL.Text,
  'address' : IDL.Text,
  'contactNumber' : IDL.Text,
  'destinationLocation' : IDL.Text,
  'pickupLocation' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'picked' : IDL.Null,
  'delivered' : IDL.Null,
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const DeliveryOrder = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'customer' : CustomerDetails,
  'createdAt' : Time,
  'lastUpdated' : Time,
  'parcelSize' : IDL.Text,
  'deliveryProof' : IDL.Opt(ExternalBlob),
  'distanceRange' : IDL.Tuple(IDL.Nat, IDL.Nat),
  'price' : IDL.Nat,
  'riderContact' : IDL.Opt(IDL.Text),
  'riderAssignment' : IDL.Opt(IDL.Text),
});
export const RiderProfile = IDL.Record({
  'hasBike' : IDL.Bool,
  'area' : IDL.Text,
  'name' : IDL.Text,
  'mobile' : IDL.Text,
  'assignedOrders' : IDL.Vec(IDL.Nat),
});
export const RiderApplication = IDL.Record({
  'hasBike' : IDL.Bool,
  'area' : IDL.Text,
  'name' : IDL.Text,
  'mobile' : IDL.Text,
  'applicationTime' : Time,
});
export const SiteContent = IDL.Record({
  'servicesList' : IDL.Text,
  'contactNumber' : IDL.Text,
  'whatsappTemplate' : IDL.Text,
  'howItWorks' : IDL.Text,
  'rates' : IDL.Vec(Rate),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addRate' : IDL.Func([Rate], [], []),
  'addRiderProfileInternal' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'applyAsRider' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignRiderToOrderInternal' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'createOrderInternal' : IDL.Func(
      [CustomerDetails, IDL.Text, IDL.Tuple(IDL.Nat, IDL.Nat), IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'getAllOrdersInternal' : IDL.Func([], [IDL.Vec(DeliveryOrder)], ['query']),
  'getAllRiderProfilesInternal' : IDL.Func(
      [],
      [IDL.Vec(RiderProfile)],
      ['query'],
    ),
  'getAssignedDeliveries' : IDL.Func([], [IDL.Vec(DeliveryOrder)], ['query']),
  'getAssignedDeliveriesForRiderInternal' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DeliveryOrder)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactNumber' : IDL.Func([], [IDL.Text], ['query']),
  'getDeliveryProof' : IDL.Func([IDL.Nat], [IDL.Opt(ExternalBlob)], ['query']),
  'getDeliveryProofForOrderInternal' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ExternalBlob)],
      ['query'],
    ),
  'getOrderDetailsInternal' : IDL.Func([IDL.Nat], [DeliveryOrder], ['query']),
  'getRates' : IDL.Func([], [IDL.Vec(Rate)], ['query']),
  'getRiderApplications' : IDL.Func([], [IDL.Vec(RiderApplication)], ['query']),
  'getSiteContent' : IDL.Func([], [SiteContent], ['query']),
  'getWhatsAppTemplate' : IDL.Func([], [IDL.Text], ['query']),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeOrderInternal' : IDL.Func([IDL.Nat], [], []),
  'removeRate' : IDL.Func([IDL.Tuple(IDL.Nat, IDL.Nat)], [], []),
  'updateDeliveryStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'updateOrderStatusInternal' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'updateOrderWithProofOfDeliveryInternal' : IDL.Func(
      [IDL.Nat, ExternalBlob],
      [],
      [],
    ),
  'updateOrderWithRiderInternal' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateSiteContent' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Vec(Rate)),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'uploadDeliveryProofInternal' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
  'uploadProofOfDelivery' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Rate = IDL.Record({
    'largeParcelPrice' : IDL.Nat,
    'minDistance' : IDL.Nat,
    'maxDistance' : IDL.Nat,
    'smallParcelPrice' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CustomerDetails = IDL.Record({
    'name' : IDL.Text,
    'address' : IDL.Text,
    'contactNumber' : IDL.Text,
    'destinationLocation' : IDL.Text,
    'pickupLocation' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'picked' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const DeliveryOrder = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'customer' : CustomerDetails,
    'createdAt' : Time,
    'lastUpdated' : Time,
    'parcelSize' : IDL.Text,
    'deliveryProof' : IDL.Opt(ExternalBlob),
    'distanceRange' : IDL.Tuple(IDL.Nat, IDL.Nat),
    'price' : IDL.Nat,
    'riderContact' : IDL.Opt(IDL.Text),
    'riderAssignment' : IDL.Opt(IDL.Text),
  });
  const RiderProfile = IDL.Record({
    'hasBike' : IDL.Bool,
    'area' : IDL.Text,
    'name' : IDL.Text,
    'mobile' : IDL.Text,
    'assignedOrders' : IDL.Vec(IDL.Nat),
  });
  const RiderApplication = IDL.Record({
    'hasBike' : IDL.Bool,
    'area' : IDL.Text,
    'name' : IDL.Text,
    'mobile' : IDL.Text,
    'applicationTime' : Time,
  });
  const SiteContent = IDL.Record({
    'servicesList' : IDL.Text,
    'contactNumber' : IDL.Text,
    'whatsappTemplate' : IDL.Text,
    'howItWorks' : IDL.Text,
    'rates' : IDL.Vec(Rate),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addRate' : IDL.Func([Rate], [], []),
    'addRiderProfileInternal' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'applyAsRider' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignRiderToOrderInternal' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'createOrderInternal' : IDL.Func(
        [CustomerDetails, IDL.Text, IDL.Tuple(IDL.Nat, IDL.Nat), IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'getAllOrdersInternal' : IDL.Func([], [IDL.Vec(DeliveryOrder)], ['query']),
    'getAllRiderProfilesInternal' : IDL.Func(
        [],
        [IDL.Vec(RiderProfile)],
        ['query'],
      ),
    'getAssignedDeliveries' : IDL.Func([], [IDL.Vec(DeliveryOrder)], ['query']),
    'getAssignedDeliveriesForRiderInternal' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DeliveryOrder)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactNumber' : IDL.Func([], [IDL.Text], ['query']),
    'getDeliveryProof' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'getDeliveryProofForOrderInternal' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'getOrderDetailsInternal' : IDL.Func([IDL.Nat], [DeliveryOrder], ['query']),
    'getRates' : IDL.Func([], [IDL.Vec(Rate)], ['query']),
    'getRiderApplications' : IDL.Func(
        [],
        [IDL.Vec(RiderApplication)],
        ['query'],
      ),
    'getSiteContent' : IDL.Func([], [SiteContent], ['query']),
    'getWhatsAppTemplate' : IDL.Func([], [IDL.Text], ['query']),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeOrderInternal' : IDL.Func([IDL.Nat], [], []),
    'removeRate' : IDL.Func([IDL.Tuple(IDL.Nat, IDL.Nat)], [], []),
    'updateDeliveryStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'updateOrderStatusInternal' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'updateOrderWithProofOfDeliveryInternal' : IDL.Func(
        [IDL.Nat, ExternalBlob],
        [],
        [],
      ),
    'updateOrderWithRiderInternal' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateSiteContent' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Vec(Rate)),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'uploadDeliveryProofInternal' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
    'uploadProofOfDelivery' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };